Repository sclorg/testing-farm-as-github-action, pull requests merged in 2024-05, with the labels that each got.

#179 fix: correctly parse tmt inputs that contain `=` (e.g. BASE64 encoded strings)
  dist/index.js
  dist/index.js.map
  dist/schema/input.js
  dist/schema/input.js.map
  src/schema/input.ts
  tests/unit/input.test.ts
Labels: type: bugfix

#175 Add release drafter workflow :memo:
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: type: ci

#180 build: update dependencies
  .eslintignore
  .eslintrc.json
  .github/workflows/lint.yml
  dist/action.js
  dist/action.js.map
  dist/error.js
  dist/error.js.map
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  dist/main.js
  dist/main.js.map
  dist/octokit.js
  dist/octokit.js.map
  dist/post.js
  dist/post.js.map
  dist/pull-request.js
  dist/pull-request.js.map
  dist/schema/input.js
  dist/schema/input.js.map
  dist/schema/testing-farm-api.js
  dist/schema/testing-farm-api.js.map
  dist/state.js
  dist/state.js.map
  dist/util.js
  dist/util.js.map
  package.json
  tests/action.test.ts
  yarn.lock
Labels: type: dependencies

#182 Update release template 🏗️
  .github/release-drafter.yml
Labels: type: documentation

#183 add issue template specific for tfaga
  .github/ISSUE_TEMPLATE/tfaga-issue.yml
Labels: type: documentation, ready for review

#184 ci: label issues based on type :label:
  .github/advanced-issue-labeler.yml
  .github/workflows/issue-labeler.yml
Labels: type: ci

#187 fix: limit size of status description to 140 character
  dist/index.js
  dist/index.js.map
  dist/pull-request.js
  dist/pull-request.js.map
  src/pull-request.ts
Labels: type: bugfix

#188 fix: job summary link :link:
  dist/index.js
  dist/index.js.map
  dist/pull-request.js
  dist/pull-request.js.map
  src/action.ts
  tests/action.test.ts
Labels: type: bugfix

#189 Make `git_url` optional :raccoon:
  .github/workflows/base-test.yml
  .github/workflows/github_summary_test.yml
  .github/workflows/secrets_test.yml
  .github/workflows/variables_test.yml
  README.md
  action.yml
Labels: type: feature
